import { useMemo, useState } from "react";
import type { OpenDialog, OrderRecord } from "../types";
import { serviceOrderStatuses, statusTone } from "../types";
import { matchesSearch, money, orderAttention, orderIsLate, orderMatchesFilter, shortDate, sortOrders } from "../workspace";
import { Icon } from "./WorkshopIcon";

export function OrdersWorkspace({ orders, budget, canCreate, openDialog, initialFilter }: { orders: OrderRecord[]; budget: boolean; canCreate: boolean; openDialog: OpenDialog; initialFilter?: string }) {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState(initialFilter || "Em aberto");
  const [view, setView] = useState<"cards" | "list">("cards");
  const [limit, setLimit] = useState(30);
  const filtered = useMemo(() => sortOrders(orders.filter((order) => matchesSearch(query, order.id, order.customer, order.bike, order.plate, order.mechanic, order.problem) && orderMatchesFilter(order, filter))), [orders, query, filter]);
  const active = orders.filter((order) => !order.closed);
  const pickFilter = (value: string) => { setFilter(value); setLimit(30); };
  return <div className="orders-workspace">
    <div className="module-heading"><div><p>Oficina</p><h1>{budget ? "Orçamentos" : "Ordens de serviço"}</h1><span>{budget ? "Da avaliação até a aprovação do cliente." : "Cada moto, seu andamento e o próximo passo."}</span></div>{canCreate && <button className="primary-button" onClick={() => openDialog(budget ? "os" : "osChoice")}><Icon name="plus" size={18}/>{budget ? "Novo orçamento" : "Novo atendimento"}</button>}</div>
    <div className="order-overview-strip"><button onClick={() => pickFilter("Em aberto")}><strong>{active.length}</strong><span>na oficina</span></button><button onClick={() => pickFilter("Atrasadas")} className="overdue-metric"><strong>{active.filter((order) => orderIsLate(order)).length}</strong><span>com prazo vencido</span></button><button onClick={() => pickFilter("Prontas")}><strong>{active.filter((order) => order.status === "Entrega").length}</strong><span>prontas para retirar</span></button></div>
    <section className="panel order-board-panel">
      <div className="list-toolbar"><label className="mini-search"><Icon name="search" size={18}/><input aria-label="Buscar atendimento" value={query} onChange={(event) => { setQuery(event.target.value); setLimit(30); }} placeholder="Cliente, placa, OS ou mecânico"/></label><div className="view-switch" aria-label="Visualização"><button aria-pressed={view === "cards"} onClick={() => setView("cards")}>Cartões</button><button aria-pressed={view === "list"} onClick={() => setView("list")}>Lista</button></div></div>
      <div className="order-status-filters" aria-label="Etapa da oficina">{["Em aberto", ...serviceOrderStatuses.filter((status) => status !== "Entrega"), "Prontas", "Entregues", "Todos"].map((status) => <button key={status} className={filter === status ? "selected" : ""} aria-pressed={filter === status} onClick={() => pickFilter(status)}>{status}<b>{orders.filter((order) => orderMatchesFilter(order, status)).length}</b></button>)}</div>
      {["Atenção", "Hoje", "Atrasadas"].includes(filter) && <div className="active-filter-banner"><span>Filtro: {filter === "Hoje" ? "Entrega prevista hoje" : filter}</span><button onClick={() => pickFilter("Em aberto")}>Remover filtro ×</button></div>}
      {!filtered.length ? <div className="workspace-empty"><span><Icon name="wrench" size={28}/></span><h3>{orders.length ? "Nenhum atendimento neste filtro" : "Tudo começa com a primeira OS"}</h3><p>{orders.length ? "Busque por outro termo ou escolha outra etapa." : "Cadastre a chegada da moto e acompanhe o serviço por aqui."}</p>{orders.length ? <button className="outline-button" onClick={() => { setQuery(""); pickFilter("Todos"); }}>Limpar filtros</button> : canCreate && <button className="primary-button" onClick={() => openDialog("osChoice")}>Abrir atendimento</button>}</div> : view === "cards" ? <div className="order-card-grid">{filtered.slice(0, limit).map((order) => <article className={`work-order-card ${orderIsLate(order) ? "is-late" : ""}`} key={order.id}>
        <header><span className="order-number">{order.id}{order.partnerOrderId ? <em className="partner-order"> · {order.partnerName || "parceiro"} {order.partnerOrderId}</em> : null}</span><span className={`status ${order.closed ? "neutral" : statusTone(order.status)}`}><i/>{order.closed ? "Entregue" : order.status === "Entrega" ? "Pronta para retirar" : order.status}</span></header><h2>{order.customer || "Cliente a identificar"}</h2><p className="order-bike"><Icon name="bike" size={17}/>{order.bike || "Moto não informada"}<b className="plate">{order.plate || "Sem placa"}</b></p><p className="order-description">{order.problem || order.service || "Abra a OS para conferir o atendimento."}</p><div className="order-card-details"><span><small>Responsável</small><strong>{order.mechanic || "Não definido"}</strong></span><span><small>Previsão</small><strong className={orderIsLate(order) ? "danger-text" : ""}>{shortDate(order.delivery)}</strong></span></div><footer><span>{orderAttention(order) || (order.total != null ? money(order.total) : "Atendimento em aberto")}</span><button className="outline-button" onClick={() => openDialog("order", order.id)}>Abrir OS <Icon name="arrow" size={16}/></button></footer>
      </article>)}</div> : <div className="table-scroll"><table><thead><tr><th>OS / Cliente</th><th>Motocicleta</th><th className="col-secondary">Responsável</th><th className="col-secondary">Previsão</th><th>Situação</th><th/></tr></thead><tbody>{filtered.slice(0, limit).map((order) => <tr key={order.id}><td><strong className="order-id">{order.id}</strong><span>{order.customer}{order.partnerOrderId ? ` · OS ${order.partnerName || "parceiro"} ${order.partnerOrderId}` : ""}</span></td><td><strong>{order.plate || "Sem placa"}</strong><span>{order.bike}</span></td><td className="col-secondary">{order.mechanic || "Não definido"}</td><td className={`col-secondary ${orderIsLate(order) ? "danger-text" : ""}`}>{shortDate(order.delivery)}</td><td><span className={`status ${order.closed ? "neutral" : statusTone(order.status)}`}><i/>{order.closed ? "Entregue" : order.status === "Entrega" ? "Pronta" : order.status}</span></td><td><button className="outline-button" onClick={() => openDialog("order", order.id)}>Abrir</button></td></tr>)}</tbody></table></div>}
      {!!filtered.length && <footer className="queue-footer"><span>{Math.min(limit, filtered.length)} de {filtered.length} atendimento(s)</span>{filtered.length > limit && <button className="outline-button" onClick={() => setLimit((value) => value + 30)}>Carregar mais</button>}</footer>}
    </section>
  </div>;
}
